---
name: build

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      buildable: ${{ steps.filter.outputs.buildable }}
    steps:
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            buildable:
              - 'slides/**'
              - 'Makefile'
              - '.github/workflows/build-doc.yaml'
              - '.github/workflows/install-dependencies'

  build:
    needs: changes
    if: needs.changes.outputs.buildable == 'true'
    runs-on: ubuntu-latest
    continue-on-error: ${{ ! matrix.stable }}
    strategy:
      matrix:
        os:
          - fedora:latest
        stable: [true]
        include:
          - os: quay.io/fedora/fedora:rawhide
            stable: false
    steps:
      - uses: actions/checkout@v6

      - name: Show OS information
        run: |
          cat /etc/os-release 2>/dev/null || \
          echo /etc/os-release not available

      - name: Install build dependencies
        run: bash .github/workflows/install-dependencies

      - name: Build documentation
        run: |
          make -C slides test all

    container:
      image: ${{matrix.os}}
      env:
        DISTRO: ${{matrix.os}}
      options: --privileged --device /dev/loop-control
